language = zh_CN
name = Player
menu_last_game = mineclonia
default_game = mineclonia
enable_server = false
server_announce = false
bind_address = 127.0.0.1
serverlist_url =
update_last_checked = 2147483647
enable_split_login_register = false
enable_damage = true
creative_mode = false
mg_name = v7
screen_w = 1280
screen_h = 720
autosave_screensize = false
fullscreen = false
video_driver = opengl3
fps_max = 90
fps_max_unfocused = 20
vsync = true
viewing_range = 128
max_block_send_distance = 10
max_block_generate_distance = 8
num_emerge_threads = 2
mesh_generation_threads = 4
enable_dynamic_shadows = true
shadow_map_texture_size = 2048
shadow_map_max_distance = 100
shadow_soft_radius = 4.0
shadow_filters = 2
shadow_strength_gamma = 0.8
shadow_map_color = true
shadow_poisson_filter = true
enable_post_processing = true
tone_mapping = true
enable_bloom = true
enable_auto_exposure = true
exposure_compensation = 0.0
enable_volumetric_lighting = true
enable_water_reflections = true
enable_waving_water = true
enable_waving_leaves = true
enable_waving_plants = true
enable_translucent_foliage = true
ambient_occlusion_gamma = 1.55
leaves_style = fancy
smooth_lighting = true
enable_fog = true
fog_start = 0.55
antialiasing = fxaa
bilinear_filter = false
trilinear_filter = false
anisotropic_filter = false
mip_map = false
gui_scaling = 0.85
hud_scaling = 0.7
font_size = 18
mono_font_size = 16
fov = 72
sound_volume = 0.6
local_quality = 柔和光影
keymap_forward = KEY_KEY_W
keymap_backward = KEY_KEY_S
keymap_left = KEY_KEY_A
keymap_right = KEY_KEY_D
keymap_jump = KEY_SPACE
keymap_sneak = KEY_LSHIFT
keymap_aux1 = KEY_LCONTROL
keymap_inventory = KEY_KEY_E
keymap_drop = KEY_KEY_Q
keymap_screenshot = KEY_F2
keymap_toggle_debug = KEY_F3
keymap_camera_mode = KEY_F5
keymap_toggle_fog =
keymap_toggle_profiler = KEY_F6
keymap_chat = KEY_KEY_T
keymap_console = KEY_F10
keymap_freemove = KEY_KEY_K
keymap_fastmove = KEY_KEY_J
keymap_noclip = KEY_KEY_H
doubletap_jump = true
map_save_interval = 5
sqlite_synchronous = 2
enable_rollback_recording = false
movement_speed_fast = 12
mcl_difficulty = normal
