"""Generate original geometric pixel UI assets. No proprietary texture inputs.
SPDX-License-Identifier: CC0-1.0
Requires Pillow only when regenerating; generated PNGs are already bundled.
"""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets'
OUT.mkdir(parents=True, exist_ok=True)

hotbar = Image.new('RGBA', (182, 22), (0, 0, 0, 140))
d = ImageDraw.Draw(hotbar)
d.rectangle((0, 0, 181, 21), outline=(18, 18, 18, 255))
for i in range(9):
    x = 1 + i * 20
    d.rectangle((x, 1, x + 19, 20), fill=(76, 76, 76, 150))
    d.line((x, 1, x + 19, 1), fill=(144, 144, 144, 245))
    d.line((x, 1, x, 20), fill=(144, 144, 144, 245))
    d.line((x + 19, 2, x + 19, 20), fill=(34, 34, 34, 245))
    d.line((x + 1, 20, x + 19, 20), fill=(34, 34, 34, 245))
hotbar.save(OUT / 'mcl_inventory_hotbar.png')

selected = Image.new('RGBA', (24, 24), (0, 0, 0, 0))
d = ImageDraw.Draw(selected)
d.rectangle((0, 0, 23, 23), outline='#242424', width=1)
d.rectangle((1, 1, 22, 22), outline='#eeeeee', width=2)
d.rectangle((3, 3, 20, 20), outline='#777777', width=1)
selected.save(OUT / 'mcl_inventory_hotbar_selected.png')

for name, top, middle, bottom in [('background', '#121212', '#293b1a', '#111a0e'), ('', '#b4ee59', '#80ba35', '#45771c')]:
    bar = Image.new('RGBA', (182, 5), '#111111')
    d = ImageDraw.Draw(bar)
    d.line((1, 1, 180, 1), fill=top)
    d.rectangle((1, 2, 180, 3), fill=middle)
    d.line((1, 4, 180, 4), fill=bottom)
    bar.transpose(Image.Transpose.ROTATE_90).save(OUT / ('mcl_experience_bar' + ('_' + name if name else '') + '.png'))
(OUT / 'texture_pack.conf').write_text('title = 缁忓吀鐏拌壊鐣岄潰\ndescription = Original geometric pixel UI, CC0\n', encoding='utf8')
(OUT / 'LICENSE.txt').write_text('Original geometric UI assets: CC0 1.0. Generated by src/generate_ui.py.\nhttps://creativecommons.org/publicdomain/zero/1.0/\n', encoding='utf8')
print(OUT)
